theme: jekyll-theme-minimal

title: [Gabriele Albertini]
description: [Research]
logo: [profile_photo_id.jpg]
show_downloads: ["true"]

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - contact.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md