theme: jekyll-theme-minimal

title: Gabriele Albertini
description: PhD Candidate at Cornell Universtiy
logo: 013839_crop_crop_big_invert_crop.png
show_downloads: false

plugins:
  - jekyll-relative-links
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - contact.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
