theme: jekyll-theme-minimal

title: Gabriele Albertini
logo: 013839_crop_crop_big_invert_crop.png
description:  <a href="/research.html">Crack zipping through a solid</a> <p><small>Copyright 2020 Gabriele Albertini. All Rights Reserved.</small></p>
show_downloads: false
auto_ids: true

plugins:
  - jekyll-relative-links
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - contact.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
